# Generated by Django 5.1.2 on 2024-11-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('CATEGORY', 'Category Offer'), ('PRODUCT', 'Product Offer')], default='CATEGORY', max_length=30),
        ),
    ]
