# Generated by Django 5.1.2 on 2024-11-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_management', '0002_offer_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('PRODUCT', 'Product Offer'), ('CATEGORY', 'Category Offer'), ('SUBCATEGORY', 'Subcategory Offer')], default='CATEGORY', max_length=30),
        ),
    ]
