# Generated by Django 5.1.2 on 2024-11-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_customuser_referral_code_customuser_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
