# Generated by Django 5.1.2 on 2024-11-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
