# Generated by Django 5.1.2 on 2024-11-21 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_order_razorpay_payment_signature'),
        ('promotion_management', '0004_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion_management.coupon'),
        ),
    ]
