# Generated by Django 5.1.2 on 2024-11-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_ordercancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercancellation',
            name='status',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
