# Generated by Django 5.1.2 on 2024-11-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_ordercancellation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercancellation',
            name='status',
        ),
    ]
