# Generated by Django 5.1.2 on 2024-11-25 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0009_remove_ordercancellation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.CharField(max_length=20)),
                ('return_explanation', models.TextField()),
                ('status', models.CharField(choices=[('REQUESTED', 'requested'), ('APPROVED', 'approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order_app.orderitem')),
            ],
        ),
    ]
