# Generated by Django 5.1.2 on 2024-11-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0010_orderreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreturn',
            name='return_explanation',
            field=models.TextField(null=True),
        ),
    ]
