# Generated by Django 5.1.2 on 2024-11-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0011_alter_orderreturn_return_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
