# Generated by Django 5.1.2 on 2024-10-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
