# Generated by Django 5.1.2 on 2024-10-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_product_is_listed_alter_productsize_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='quantity',
            field=models.IntegerField(default=0, null=0),
            preserve_default=False,
        ),
    ]
