# Generated by Django 5.1.2 on 2024-10-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_productsize_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
