# Generated by Django 5.1.2 on 2024-11-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0009_remove_product_price_productvariant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
