# Generated by Django 5.1.2 on 2024-11-13 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0013_remove_productvariant_offer_product_offer'),
        ('promotion_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion_management.offer'),
        ),
    ]
