# Generated by Django 5.1.2 on 2024-11-19 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0014_alter_product_offer'),
        ('promotion_management', '0003_alter_offer_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion_management.offer'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion_management.offer'),
        ),
    ]
