# Generated by Django 5.1.2 on 2024-11-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='transacton_type',
            new_name='transaction_type',
        ),
    ]
