# Generated by Django 5.1.2 on 2024-11-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0003_walletrazrorpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('CANCELLATION', 'Cancellation'), ('CREDIT', 'Credited'), ('DEBIT', 'Debited'), ('REFERRAL', 'Referral')], max_length=20),
        ),
    ]
